FROM chef/inspec:current

COPY ./src/backend ./project/backend
COPY ./src/frontend ./project/frontend
COPY ./tests ./project/tests
WORKDIR ./project/tests
ENTRYPOINT ["inspec", "exec",  "<test file name with path>"]